logging:
  level:
    org.springframework.web: ERROR
    com.munteanu: DEBUG

spring.data.mongodb.uri: mongodb://localhost:27017/camel

mongo:
  host: localhost
  port: 27017
  database: camel


rabbitmq:
  addresses: localhost:5672
  username: guest
  password: guest
  virtualHost: /
  useSsl: false
  maxConcurrentConsumers: 5
  messageTtl: 30000